---
abstract: 'Convert cpan distribution from BackPAN to a git repository'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  File::HomeDir: '0.91'
  HTTP::Date: '0'
  Module::Build: '0.28'
  Test::More: '0.94'
  URI::file: '0'
  perl: '5.010001'
configure_requires:
  Git::Wrapper: '0'
  Module::Build: '0.28'
  Sort::Versions: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-cpangitify
recommends:
  PerlX::Maybe::XS: '0'
requires:
  Archive::Extract: '0'
  CPAN::ReleaseHistory: '0'
  File::Copy::Recursive: '0'
  File::chdir: '0'
  Git::Wrapper: '0'
  HTTP::Tiny: '0'
  IPC::System::Simple: '0'
  JSON::PP: '0'
  Path::Class: '0.26'
  PerlX::Maybe: '0.003'
  URI: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/plicease/App-cpangitify/issues
  homepage: http://perl.wdlabs.com/App-cpangitify
  repository: git://github.com/plicease/App-cpangitify.git
version: '0.12'
